Repository pixielabs/cavy-app, pull requests merged in 2020-05, with the labels that each got.

#10 Add more examples to documentation
  docs/api/helpers.md
  docs/api/tester.md
Labels: documentation, ready

#11 add --xml flag to cli docs
  docs/api/commands.md
Labels: documentation

#13 remove custom helper from findComponent() example
  docs/api/helpers.md
Labels: documentation

#15 Tidy up docs
  docs/api/commands.md
  docs/api/test-helpers.md
  docs/api/test-hooks.md
  docs/api/tester.md
  docs/getting-started/hooking-up-components.md
  docs/getting-started/installing.md
  docs/getting-started/running-tests.md
  docs/getting-started/sample-app.md
  docs/getting-started/setting-cavy-up.md
  docs/getting-started/writing-tests.md
  docs/guides/writing-spec-helpers.md
  website/sidebars.json
  website/siteConfig.js
Labels: for review
